// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OncovoApi.Database;

#nullable disable

namespace OncovoApi.Migrations
{
    [DbContext(typeof(DestinoDbContext))]
    partial class DestinoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("OncovoApi.Model.Destino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("CidadeNome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cidade");

                    b.Property<string>("EstadoPaisNome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("estado_pais");

                    b.HasKey("Id");

                    b.ToTable("destinos", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
